compressionLevel: mixed

enableGlobalCache: false

npmPublishAccess: public

yarnPath: .yarn/releases/yarn-4.0.1.cjs

# nodeLinker: node-modules

packageExtensions:
  "@docusaurus/bundler@*":
    dependencies:
      "@docusaurus/faster": "*"
  "@docusaurus/theme-common@*":
    dependencies:
      "@docusaurus/plugin-content-docs": "*"
  "terser-webpack-plugin@*":
    dependencies:
      "@swc/core": "*"
  "css-minimizer-webpack-plugin@*":
    dependencies:
      "lightningcss": "*"


